In [1]:
import pandas as pd
import numpy as np
import sys 
sys.path.insert(0, '../DevCode')

In [2]:
from DataManager import SimpleTokenizer

In [3]:
df = pd.read_csv('./Data/malicious_phish.csv')

In [4]:
df

url        type
0                                        br-icloud.com.br    phishing
1                     mp3raid.com/music/krizz_kaliko.html      benign
2                         bopsecrets.org/rexroth/cr/1.htm      benign
3       http://www.garage-pirenne.be/index.php?option=...  defacement
4       http://adventure-nicaragua.net/index.php?optio...  defacement
...                                                   ...         ...
651186            xbox360.ign.com/objects/850/850402.html    phishing
651187       games.teamxbox.com/xbox-360/1860/Dead-Space/    phishing
651188         www.gamespot.com/xbox360/action/deadspace/    phishing
651189      en.wikipedia.org/wiki/Dead_Space_(video_game)    phishing
651190          www.angelfire.com/goth/devilmaycrytonite/    phishing

[651191 rows x 2 columns]

In [5]:
tm = SimpleTokenizer()

In [6]:
df['string_tokens'] = tm.tokenize_column(df['url'])

In [7]:
df

url        type  \
0                                        br-icloud.com.br    phishing   
1                     mp3raid.com/music/krizz_kaliko.html      benign   
2                         bopsecrets.org/rexroth/cr/1.htm      benign   
3       http://www.garage-pirenne.be/index.php?option=...  defacement   
4       http://adventure-nicaragua.net/index.php?optio...  defacement   
...                                                   ...         ...   
651186            xbox360.ign.com/objects/850/850402.html    phishing   
651187       games.teamxbox.com/xbox-360/1860/Dead-Space/    phishing   
651188         www.gamespot.com/xbox360/action/deadspace/    phishing   
651189      en.wikipedia.org/wiki/Dead_Space_(video_game)    phishing   
651190          www.angelfire.com/goth/devilmaycrytonite/    phishing   

                                            string_tokens  
0                          [br, -, icloud, ., com, ., br]  
1       [mp3raid, ., com, /, music, /, krizz_kaliko, ....  
2       [bopsecrets, ., org, /, rexroth, /, cr, /, 1, ...  
3       [http, :, /, /, www, ., garage, -, pirenne, .,...  
4       [http, :, /, /, adventure, -, nicaragua, ., ne...  
...                                                   ...  
651186  [xbox360, ., ign, ., com, /, objects, /, 850, ...  
651187  [games, ., teamxbox, ., com, /, xbox, -, 360, ...  
651188  [www, ., gamespot, ., com, /, xbox360, /, acti...  
651189  [en, ., wikipedia, ., org, /, wiki, /, Dead_Sp...  
651190  [www, ., angelfire, ., com, /, goth, /, devilm...  

[651191 rows x 3 columns]

In [8]:
df['tokens'] = df['string_tokens'].apply(tm.convert_tokens_to_ids)

In [9]:
df['tokens']

0                                     [1, 2, 3, 4, 5, 4, 1]
1                              [6, 4, 5, 7, 8, 7, 9, 4, 10]
2                   [11, 4, 12, 7, 13, 7, 14, 7, 15, 4, 16]
3         [17, 18, 7, 7, 19, 4, 20, 2, 21, 4, 22, 7, 23,...
4         [17, 18, 7, 7, 36, 2, 37, 4, 38, 7, 23, 4, 24,...
                                ...                        
651186    [62048, 4, 3247, 4, 5, 7, 3248, 7, 3758, 7, 62...
651187    [2686, 4, 45660, 4, 5, 7, 23449, 2, 4843, 7, 1...
651188    [19, 4, 8613, 4, 5, 7, 62048, 7, 5920, 7, 4298...
651189    [187, 4, 188, 4, 12, 7, 189, 7, 627327, 327, 3...
651190        [19, 4, 15712, 4, 5, 7, 612669, 7, 627328, 7]
Name: tokens, Length: 651191, dtype: object

In [10]:
df = df.rename({'type':'target'},axis=1)
df

url      target  \
0                                        br-icloud.com.br    phishing   
1                     mp3raid.com/music/krizz_kaliko.html      benign   
2                         bopsecrets.org/rexroth/cr/1.htm      benign   
3       http://www.garage-pirenne.be/index.php?option=...  defacement   
4       http://adventure-nicaragua.net/index.php?optio...  defacement   
...                                                   ...         ...   
651186            xbox360.ign.com/objects/850/850402.html    phishing   
651187       games.teamxbox.com/xbox-360/1860/Dead-Space/    phishing   
651188         www.gamespot.com/xbox360/action/deadspace/    phishing   
651189      en.wikipedia.org/wiki/Dead_Space_(video_game)    phishing   
651190          www.angelfire.com/goth/devilmaycrytonite/    phishing   

                                            string_tokens  \
0                          [br, -, icloud, ., com, ., br]   
1       [mp3raid, ., com, /, music, /, krizz_kaliko, ....   
2       [bopsecrets, ., org, /, rexroth, /, cr, /, 1, ...   
3       [http, :, /, /, www, ., garage, -, pirenne, .,...   
4       [http, :, /, /, adventure, -, nicaragua, ., ne...   
...                                                   ...   
651186  [xbox360, ., ign, ., com, /, objects, /, 850, ...   
651187  [games, ., teamxbox, ., com, /, xbox, -, 360, ...   
651188  [www, ., gamespot, ., com, /, xbox360, /, acti...   
651189  [en, ., wikipedia, ., org, /, wiki, /, Dead_Sp...   
651190  [www, ., angelfire, ., com, /, goth, /, devilm...   

                                                   tokens  
0                                   [1, 2, 3, 4, 5, 4, 1]  
1                            [6, 4, 5, 7, 8, 7, 9, 4, 10]  
2                 [11, 4, 12, 7, 13, 7, 14, 7, 15, 4, 16]  
3       [17, 18, 7, 7, 19, 4, 20, 2, 21, 4, 22, 7, 23,...  
4       [17, 18, 7, 7, 36, 2, 37, 4, 38, 7, 23, 4, 24,...  
...                                                   ...  
651186  [62048, 4, 3247, 4, 5, 7, 3248, 7, 3758, 7, 62...  
651187  [2686, 4, 45660, 4, 5, 7, 23449, 2, 4843, 7, 1...  
651188  [19, 4, 8613, 4, 5, 7, 62048, 7, 5920, 7, 4298...  
651189  [187, 4, 188, 4, 12, 7, 189, 7, 627327, 327, 3...  
651190      [19, 4, 15712, 4, 5, 7, 612669, 7, 627328, 7]  

[651191 rows x 4 columns]

In [11]:
df = df.drop(['url', 'string_tokens'],axis=1)

In [12]:
df['sizes'] = [len(i) for i in df['tokens']]

In [20]:
df

target                                             tokens  sizes
0         phishing                              [1, 2, 3, 4, 5, 4, 1]      7
1           benign                       [6, 4, 5, 7, 8, 7, 9, 4, 10]      9
2           benign            [11, 4, 12, 7, 13, 7, 14, 7, 15, 4, 16]     11
3       defacement  [17, 18, 7, 7, 19, 4, 20, 2, 21, 4, 22, 7, 23,...     31
4       defacement  [17, 18, 7, 7, 36, 2, 37, 4, 38, 7, 23, 4, 24,...     25
...            ...                                                ...    ...
651186    phishing  [62048, 4, 3247, 4, 5, 7, 3248, 7, 3758, 7, 62...     13
651187    phishing  [2686, 4, 45660, 4, 5, 7, 23449, 2, 4843, 7, 1...     16
651188    phishing  [19, 4, 8613, 4, 5, 7, 62048, 7, 5920, 7, 4298...     12
651189    phishing  [187, 4, 188, 4, 12, 7, 189, 7, 627327, 327, 3...     12
651190    phishing      [19, 4, 15712, 4, 5, 7, 612669, 7, 627328, 7]     10

[651191 rows x 3 columns]

In [13]:
df['sizes'].value_counts()

sizes
9      65752
11     52063
13     47651
17     40627
15     40475
       ...  
265        1
263        1
243        1
307        1
363        1
Name: count, Length: 280, dtype: int64

In [14]:
df['sizes'].describe()

count    651191.000000
mean         17.920790
std          14.697409
min           1.000000
25%           9.000000
50%          13.000000
75%          23.000000
max         582.000000
Name: sizes, dtype: float64

In [36]:
mean = df['sizes'].mean()
std = df['sizes'].std()

In [42]:
clipped_data = df[(df['sizes'] >= (mean - 2*std)) & (df['sizes'] <= (mean + 2*std))]

In [43]:
data = df.loc[clipped_data.index]

In [66]:
targets = df['target'].loc[clipped_data.index]

In [44]:
data['sizes'].max()

47

In [45]:
data

target                                             tokens  sizes
0         phishing                              [1, 2, 3, 4, 5, 4, 1]      7
1           benign                       [6, 4, 5, 7, 8, 7, 9, 4, 10]      9
2           benign            [11, 4, 12, 7, 13, 7, 14, 7, 15, 4, 16]     11
3       defacement  [17, 18, 7, 7, 19, 4, 20, 2, 21, 4, 22, 7, 23,...     31
4       defacement  [17, 18, 7, 7, 36, 2, 37, 4, 38, 7, 23, 4, 24,...     25
...            ...                                                ...    ...
651186    phishing  [62048, 4, 3247, 4, 5, 7, 3248, 7, 3758, 7, 62...     13
651187    phishing  [2686, 4, 45660, 4, 5, 7, 23449, 2, 4843, 7, 1...     16
651188    phishing  [19, 4, 8613, 4, 5, 7, 62048, 7, 5920, 7, 4298...     12
651189    phishing  [187, 4, 188, 4, 12, 7, 189, 7, 627327, 327, 3...     12
651190    phishing      [19, 4, 15712, 4, 5, 7, 612669, 7, 627328, 7]     10

[629456 rows x 3 columns]

In [51]:
max_length = 0

for i in data['tokens'].values:
    if len(i) > max_length:
        max_length = len(i)

In [52]:
max_length

47

In [57]:
array_data = [np.array(i) for i in data['tokens'].values]

In [58]:
array_data

[array([1, 2, 3, 4, 5, 4, 1]),
 array([ 6,  4,  5,  7,  8,  7,  9,  4, 10]),
 array([11,  4, 12,  7, 13,  7, 14,  7, 15,  4, 16]),
 array([17, 18,  7,  7, 19,  4, 20,  2, 21,  4, 22,  7, 23,  4, 24, 25, 26,
        27, 28, 29, 30, 27, 31, 29, 32, 27, 33, 29, 34, 27, 35]),
 array([17, 18,  7,  7, 36,  2, 37,  4, 38,  7, 23,  4, 24, 25, 26, 27, 39,
        29, 40, 27, 41, 29, 42, 27, 43]),
 array([17, 18,  7,  7, 44,  4, 38,  7, 45,  7, 46,  2, 47,  7, 48,  2, 49,
         2, 50,  2, 51,  2, 52,  2, 53,  2, 54,  2, 55,  2, 56,  2, 57,  2,
        58,  2, 59,  2, 60,  2, 48,  2, 61,  2, 62,  4, 10]),
 array([63,  4, 64,  4,  5,  7, 65,  7, 66,  7, 67,  7, 32,  7, 68,  7, 69,
         2, 70]),
 array([71,  4,  5,  7, 25, 72, 27, 73,  2, 74,  2, 75]),
 array([17, 18,  7,  7, 19,  4, 76,  4,  5,  7, 77,  2, 78]),
 array([79,  4,  5,  7, 80,  7, 81,  2, 82,  2, 83,  2, 84,  2, 85]),
 array([86,  4,  5,  7, 87,  7, 88,  7, 89,  2, 52,  2, 90,  2, 91,  4, 92]),
 array([17, 18,  7,  7, 19,  4, 9

In [59]:
max_length

47

In [60]:
array_data

[array([1, 2, 3, 4, 5, 4, 1]),
 array([ 6,  4,  5,  7,  8,  7,  9,  4, 10]),
 array([11,  4, 12,  7, 13,  7, 14,  7, 15,  4, 16]),
 array([17, 18,  7,  7, 19,  4, 20,  2, 21,  4, 22,  7, 23,  4, 24, 25, 26,
        27, 28, 29, 30, 27, 31, 29, 32, 27, 33, 29, 34, 27, 35]),
 array([17, 18,  7,  7, 36,  2, 37,  4, 38,  7, 23,  4, 24, 25, 26, 27, 39,
        29, 40, 27, 41, 29, 42, 27, 43]),
 array([17, 18,  7,  7, 44,  4, 38,  7, 45,  7, 46,  2, 47,  7, 48,  2, 49,
         2, 50,  2, 51,  2, 52,  2, 53,  2, 54,  2, 55,  2, 56,  2, 57,  2,
        58,  2, 59,  2, 60,  2, 48,  2, 61,  2, 62,  4, 10]),
 array([63,  4, 64,  4,  5,  7, 65,  7, 66,  7, 67,  7, 32,  7, 68,  7, 69,
         2, 70]),
 array([71,  4,  5,  7, 25, 72, 27, 73,  2, 74,  2, 75]),
 array([17, 18,  7,  7, 19,  4, 76,  4,  5,  7, 77,  2, 78]),
 array([79,  4,  5,  7, 80,  7, 81,  2, 82,  2, 83,  2, 84,  2, 85]),
 array([86,  4,  5,  7, 87,  7, 88,  7, 89,  2, 52,  2, 90,  2, 91,  4, 92]),
 array([17, 18,  7,  7, 19,  4, 9

In [61]:
matrix_list = []
for i in array_data:
    new_vector = np.zeros(max_length)
    current_vector_size = i.shape[0]
    new_vector[:current_vector_size] = i
    matrix_list.append(new_vector)


In [62]:
matrix_main = np.vstack(matrix_list)

In [26]:
del matrix_list

In [63]:
matrix_main

array([[1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.0000e+00, 4.0000e+00, 5.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.1000e+01, 4.0000e+00, 1.2000e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [1.9000e+01, 4.0000e+00, 8.6130e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.8700e+02, 4.0000e+00, 1.8800e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.9000e+01, 4.0000e+00, 1.5712e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [64]:
matrix_main[0]

array([1., 2., 3., 4., 5., 4., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
matrix_main

array([[1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.0000e+00, 4.0000e+00, 5.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.1000e+01, 4.0000e+00, 1.2000e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [1.9000e+01, 4.0000e+00, 8.6130e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.8700e+02, 4.0000e+00, 1.8800e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.9000e+01, 4.0000e+00, 1.5712e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [68]:
from lightgbm import LGBMClassifier
model = LGBMClassifier(
    boosting_type='rf',
    max_depth=6,
    num_leaves=6 ** 2,
    n_estimators=200,
    learning_rate=0.05,
    min_child_samples=100,
    random_state=5,
    n_jobs=4,
    colsample_bytree=0.5
)

In [72]:
ap = int(matrix_main.shape[0] * 0.8)

In [73]:
ap

503564

In [77]:
targets.value_counts()

target
benign        417323
phishing       92513
defacement     90520
malware        29100
Name: count, dtype: int64

In [79]:
target_list = []
for i in targets.values:
    if i == 'benign':
        target_list.append(0)
    else:
        target_list.append(1)

In [80]:
targets = target_list

In [82]:
train = (matrix_main[:ap], targets[:ap])
test = (matrix_main[ap:], targets[ap:])

In [83]:
train

(array([[  1.,   2.,   3., ...,   0.,   0.,   0.],
        [  6.,   4.,   5., ...,   0.,   0.,   0.],
        [ 11.,   4.,  12., ...,   0.,   0.,   0.],
        ...,
        [ 17.,  18.,   7., ...,   0.,   0.,   0.],
        [251.,  18.,   7., ...,   0.,   0.,   0.],
        [251.,  18.,   7., ...,   0.,   0.,   0.]]),
 [1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,

In [84]:
test

(array([[1.7000e+01, 1.8000e+01, 7.0000e+00, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.7000e+01, 1.8000e+01, 7.0000e+00, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.7000e+01, 1.8000e+01, 7.0000e+00, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [1.9000e+01, 4.0000e+00, 8.6130e+03, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.8700e+02, 4.0000e+00, 1.8800e+02, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9000e+01, 4.0000e+00, 1.5712e+04, ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]]),
 [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,